version: '3.1'

services:
  db:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $PGPASSWORD
    ports:
        - 5433:5432
    networks:
      - botnet


  tgbot:
    container_name: bot
    build:
      context: .
    restart: always
    env_file:
      - ".env"
    volumes:
      - .:/src
    depends_on:
      - db
    networks:
      - botnet

networks:
  botnet:
    driver: bridge
